name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Check linting and package compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install required package deps
        run: yarn

      - name: Lint package
        run: yarn lint

      - name: Build
        run: yarn build
