name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Check linting and package compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install required package deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Lint and build the package
        uses: borales/actions-yarn@v4
        with:
          cmd: lint && build
